### ISSUE TITLE
Missing games and unfunctional play button 

### ISSUE THREAD

**Issue by Spyromaniac31** [LeonardFiedrowicz/galaxy-integration-cemu#9]
I have two games in my Wii U Games folder: Smash Bros. and BOTW. Only BOTW shows up in GOG. Both games are located in the same place. When I click play on BOTW I’m GOG, nothing happens.

**Comment by LeonardFiedrowicz** [comment]
The latest commit has an issue of filtering out too many games. You can try the latest release in that case. Otherwise, can you upload the meta.xml in the meta folder from smash 4?

For the other issue I would need the log file located at 
`"C:\ProgramData\GOG.com\Galaxy\logs\plugin-nwiiu-1023214b-fd5d-45fd-9671-c080e92b03bb.log"`
I can't launch cemu if you require admin permission to start cemu.

**Comment by Spyromaniac31** [comment]
Here are the files. Cemu shouldn't need admin permission since it's on my desktop.

[Cemu GOG stuff.zip](https://github.com/LeonardFiedrowicz/galaxy-integration-cemu/files/3655325/Cemu.GOG.stuff.zip)

**Comment by LeonardFiedrowicz** [comment]
I reversed that "filter out updates" thing in the master branch as well now. That should fix the missing games not showing (might show updates as well now though, if you have them in the same folder).

Not sure why launching games doen't work. There is an error about self.game_times being None though.

It doesn't seem to show that you are launching any games in that log. Is the Launch button greyed out in GOG? It might be because the plugin crashes when importing game times.

**Comment by Spyromaniac31** [comment]
The latest version worked, all my games appear now. I went and looked at the log files, and the problem seems to be that GOG is trying to get to C:\ .... \Desktop\Cemu\cemu.exe, but my Desktop is located on the F: drive.
